/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dado;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import tablero.Tablero;
/**
 *
 * @author Administrador
 */
public class Dado extends javax.swing.JFrame implements Runnable{

    private ArrayList <ImageIcon> lado;
    private int c;
    private Thread hilo;
    private int tir;
    private boolean primera;
    private int veces;
    
    public Dado() {
        initComponents();
        rellenarArrayList();
        dadoL.setIcon(lado.get(0));
        primera = true;
    }

    public Thread getHilo(){
        return hilo;
    }
    
    public boolean getFirst(){
        return primera;
    }
 
    public ArrayList<ImageIcon> getLado(){
        return lado;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelP = new javax.swing.JPanel();
        dadoL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        dadoL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dadoLMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelPLayout = new javax.swing.GroupLayout(panelP);
        panelP.setLayout(panelPLayout);
        panelPLayout.setHorizontalGroup(
            panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dadoL, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );
        panelPLayout.setVerticalGroup(
            panelPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dadoL, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dadoLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dadoLMouseClicked
      

    }//GEN-LAST:event_dadoLMouseClicked

    public void girarDado(){
        //Manejamos si es la primera o la segunda pulsacion en el dado, para ponerlo a girar o pararlo
          if(primera){
            hilo = new Thread(this);
            hilo.start();
            primera = false;
        }else{
            hilo.stop();
            primera = true;
        }
          
          
        String imagen = dadoL.getIcon().toString();
        imagen = imagen.substring(imagen.length()-6, imagen.length()-4);
        int im = Integer.valueOf(imagen);
        if(im >= 00 && im <= 05 || im >= 66 && im <= 71)
            dadoL.setIcon(lado.get(0));
        else
            if(im >= 06 && im <= 11 || im >= 42 && im <= 47)
                dadoL.setIcon(lado.get(45));
            else
                if(im >= 12 && im <= 23)
                    dadoL.setIcon(lado.get(18));
                else
                    if(im >= 24 && im <= 29 || im >= 60 && im <= 65)
                        dadoL.setIcon(lado.get(63));
                    else
                        if(im >= 30 && im <= 41)
                            dadoL.setIcon(lado.get(36));
                        else
                            if(im >= 48 && im <= 59)
                                dadoL.setIcon(lado.get(54));
        imagen = dadoL.getIcon().toString();
        imagen = imagen.substring(imagen.length()-6, imagen.length()-4);
        im = Integer.valueOf(imagen);
        switch(im){
            case 0:{
                tir = 6;
            }break;
            case 45:{
                tir = 2;
            }break;
            case 18:{
                tir = 3;
            }break;
            case 63:{
                tir = 5;
            }break;
            case 36:{
                tir = 1;
            }break;
            case 54:{
                tir = 4;
            }
        }
    }
    public int valorDado(){
        return tir;
    }
    
    public void mostrarDado(){
        if(c > 71)
            c=0;
        dadoL.setIcon(lado.get(c));
    }
    
    public JLabel getDado(){
        return dadoL;
    }
    public void rellenarArrayList(){
        lado = new ArrayList();
        for(int i=0; i<72; i++){
            String k = String.format("%02d", i);
            lado.add(new ImageIcon(getClass().getResource("../imagenes/dado/dado"+ k + ".png")));
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel dadoL;
    private javax.swing.JPanel panelP;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        
        while(true) {
            c++;
            mostrarDado();
            repaint();
            try {       
                Thread.sleep(10);      
            }      catch(InterruptedException e) {
                   }
        }
    }
}
